%% Final test of microglia classifier


% Performs the one-time final evaluation of the selected classifier
% using the previously untouched Test set

% Classifier:
%   Model: Bagged Trees
%   MinLeafSize: 1
%   Number of trees: 100
%   Predictors: 9 morphology features

clear;
clc;
close all;

%% Prepare machine learning data

prepareMicrogliaMLDataset;

%% Load the trained classifier

modelFile = fullfile( ...
    'Results_3D_Microglia', ...
    'Microglia_Classifier.mat');

if ~isfile(modelFile)
    error(['Trained classifier was not found: %s\n' ...
           'Run trainMicrogliaClassifier.m first.'], modelFile);
end

loadedModel = load(modelFile);

microgliaClassifier = loadedModel.microgliaClassifier;
featureNames = loadedModel.featureNames;
minimumLeafSize = loadedModel.minimumLeafSize;
numberOfTrees = loadedModel.numberOfTrees;
classNames = loadedModel.classNames;

fprintf('\n--- FINAL MICROGLIA CLASSIFIER TEST ---\n');

fprintf('Test cells: %d\n', size(XTest,1));

fprintf('\nFrozen classifier:\n');
fprintf('  Model: Bagged Trees\n');
fprintf('  MinLeafSize: %d\n', minimumLeafSize);
fprintf('  Number of trees: %d\n', numberOfTrees);
fprintf('  Number of predictors: %d\n', length(featureNames));



%% Check frozen settings

if minimumLeafSize ~= 1 || numberOfTrees ~= 100
    error(['The saved classifier does not use the expected frozen ' ...
           'settings: MinLeafSize=1 and NumberOfTrees=100.']);
end

%% Predict the test set

testPrediction = predict( ...
    microgliaClassifier, ...
    XTest);

%% Calculate test metrics

[testMetrics, testConfusionMatrix] = ...
    calculateClassificationMetrics( ...
        YTest, ...
        testPrediction, ...
        classNames);

%% Print final test results

fprintf('\n--- FINAL TEST RESULTS ---\n');

fprintf('Overall accuracy:  %.4f  (%.1f%%)\n', ...
    testMetrics.OverallAccuracy, ...
    100 * testMetrics.OverallAccuracy);

fprintf('Balanced accuracy: %.4f  (%.1f%%)\n', ...
    testMetrics.BalancedAccuracy, ...
    100 * testMetrics.BalancedAccuracy);

fprintf('Macro F1:          %.4f\n', ...
    testMetrics.MacroF1);

numberCorrect = sum(testPrediction == YTest);
numberIncorrect = numel(YTest) - numberCorrect;

fprintf('\nCorrect classifications:   %d / %d\n', ...
    numberCorrect, numel(YTest));

fprintf('Incorrect classifications: %d / %d\n', ...
    numberIncorrect, numel(YTest));

%% Per-class test results

testClassMetrics = table( ...
    string(classNames), ...
    testMetrics.Precision, ...
    testMetrics.Recall, ...
    testMetrics.F1, ...
    'VariableNames', { ...
        'Class', ...
        'Precision', ...
        'Recall', ...
        'F1'});

fprintf('\n--- PER-CLASS TEST METRICS ---\n');
disp(testClassMetrics);


%% Print numeric confusion matrix

confusionMatrixTable = array2table( ...
    testConfusionMatrix, ...
    'VariableNames', strcat("Predicted_", classNames'), ...
    'RowNames', strcat("True_", classNames'));

fprintf('\n--- TEST CONFUSION MATRIX ---\n');
disp(confusionMatrixTable);

%% Display test confusion matrix

figure(1);

trueLabelsForPlot = reordercats( ...
    YTest, ...
    classNames);

predictedLabelsForPlot = reordercats( ...
    testPrediction, ...
    classNames);

chartHandle = confusionchart( ...
    trueLabelsForPlot, ...
    predictedLabelsForPlot);

chartHandle.Title = ...
    'Bagged Trees Classifier - Final Test Set';

%% Save final test summary

resultsFolder = 'Results_3D_Microglia';

if ~isfolder(resultsFolder)
    mkdir(resultsFolder);
end

summaryTable = table( ...
    minimumLeafSize, ...
    numberOfTrees, ...
    testMetrics.OverallAccuracy, ...
    testMetrics.BalancedAccuracy, ...
    testMetrics.MacroF1, ...
    numberCorrect, ...
    numberIncorrect, ...
    'VariableNames', { ...
        'MinLeafSize', ...
        'NumTrees', ...
        'OverallAccuracy', ...
        'BalancedAccuracy', ...
        'MacroF1', ...
        'Correct', ...
        'Incorrect'});

summaryFile = fullfile( ...
    resultsFolder, ...
    'Microglia_Final_Test_Summary.csv');

classMetricsFile = fullfile( ...
    resultsFolder, ...
    'Microglia_Final_Test_PerClass.csv');

predictionsFile = fullfile( ...
    resultsFolder, ...
    'Microglia_Final_Test_Predictions.csv');

writetable(summaryTable, summaryFile);
writetable(testClassMetrics, classMetricsFile);


%% Save cell-by-cell test predictions

datasetFile = 'Microglia_Labelled_Dataset.csv';

fullData = readtable( ...
    datasetFile, ...
    'TextType', 'string');

validLabels = ["Amoeboid", "Activated", "Ramified"];

testRows = ...
    ismember(fullData.MorphologyLabel, validLabels) & ...
    fullData.DatasetSplit == "Test";

testPredictionTable = table( ...
    fullData.SourceFile(testRows), ...
    fullData.ObjectID(testRows), ...
    fullData.MorphologyLabel(testRows), ...
    string(testPrediction), ...
    fullData.WasSeparated(testRows), ...
    'VariableNames', { ...
        'SourceFile', ...
        'ObjectID', ...
        'TrueLabel', ...
        'PredictedLabel', ...
        'WasSeparated'});

testPredictionTable.Correct = ...
    testPredictionTable.TrueLabel == ...
    testPredictionTable.PredictedLabel;

writetable( ...
    testPredictionTable, ...
    predictionsFile);


%% Final message

fprintf('\nFinal Test results saved to:\n');
fprintf('  %s\n', summaryFile);
fprintf('  %s\n', classMetricsFile);
fprintf('  %s\n', predictionsFile);

fprintf('\nFINAL TEST COMPLETE.\n');

%% Local function

function [metrics, confusionMatrix] = ...
    calculateClassificationMetrics( ...
        trueLabels, predictedLabels, classNames)

confusionMatrix = confusionmat( ...
    trueLabels, ...
    predictedLabels, ...
    'Order', categorical(classNames, classNames));

numberOfClasses = numel(classNames);

precision = zeros(numberOfClasses,1);
recall = zeros(numberOfClasses,1);
f1 = zeros(numberOfClasses,1);

for classIndex = 1:numberOfClasses

    truePositive = ...
        confusionMatrix(classIndex,classIndex);

    falsePositive = ...
        sum(confusionMatrix(:,classIndex)) - truePositive;

    falseNegative = ...
        sum(confusionMatrix(classIndex,:)) - truePositive;

    if truePositive + falsePositive > 0
        precision(classIndex) = ...
            truePositive / ...
            (truePositive + falsePositive);
    else
        precision(classIndex) = 0;
    end

    if truePositive + falseNegative > 0
        recall(classIndex) = ...
            truePositive / ...
            (truePositive + falseNegative);
    else
        recall(classIndex) = 0;
    end

    if precision(classIndex) + recall(classIndex) > 0
        f1(classIndex) = ...
            2 * precision(classIndex) * recall(classIndex) / ...
            (precision(classIndex) + recall(classIndex));
    else
        f1(classIndex) = 0;
    end

end

overallAccuracy = ...
    sum(diag(confusionMatrix)) / ...
    sum(confusionMatrix,'all');

balancedAccuracy = mean(recall);
macroF1 = mean(f1);

metrics.OverallAccuracy = overallAccuracy;
metrics.BalancedAccuracy = balancedAccuracy;
metrics.MacroF1 = macroF1;

metrics.Precision = precision;
metrics.Recall = recall;
metrics.F1 = f1;

end
